name: car-sales
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pandas>=2.2.2,<3.0.0
  - scikit-learn>=1.5.1,<2.0.0
  - lightgbm>=4.6.0
  - catboost>=1.2.5
  - matplotlib>=3.9.2
  - seaborn>=0.13.2
  - xgboost>=2.1.1
  - pyyaml>=6.0
  - joblib>=1.3.0
  - pytest>=7.2.1
  - pytest-cov>=4.0.0
  - jupyterlab>=4.2.4
  - pip:
    - -e .
    - plotly>=5.24.0
    - debugpy>=1.8.5
