# config/params.yaml
decision_tree:
 max_depth: [1, 2, 3, 4, 5, 6]
 min_samples_split: [2, 4, 6, 8]
 min_samples_leaf: [2, 4, 6, 8]

random_forest:
 n_estimators: [10, 20, 40]
 max_depth: [1, 2, 3, 4, 5, 6]
 min_samples_split: [2, 4, 6, 8]
 min_samples_leaf: [2, 4, 6, 8]

catboost:
 depth: [4, 6, 10]
 learning_rate: [0.01, 0.05, 0.1, 0.2]
 random_strength: [1, 5, 10]

xgboost:
 max_depth: [4, 6, 8]
 n_estimators: [50, 100]
 learning_rate: [0.05, 0.1]
 subsample: [0.6, 0.8]

lightgbm:  
 n_estimators: [100, 150, 300]
 learning_rate: [0.1, 0.2, 0.5]
 max_depth: [5, 8, 10]
 subsample: [0.6, 0.7, 0.8]

# test from selected models
test_models: 
 selected_models: ["LGBM", "LGBM_log", "XGBoost_log", "RF_log", "DT_log"] 

